name: Github Actions. Custom Action para modificar el readme de nuestro proyecto.

on:
  push:
    branches:
      - github_action_readme

jobs:
  job1:
    name: test-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run jest tests
        run: npm install jest
          npm test

  job2:
    name: Generar meme
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ejecutar acción de memezación
        uses: Cristiannett/githubActions_examples@meme_v1
        with:
          test_result: ${{ needs.job1.outputs.test_result }}

      - name: Commit changes
        uses: actions/add-and-commit@v7
        with:
          branch: github_action_readme
          commit-message: Actualizar README con meme de resultados de pruebas
