name: Github Actions. Custom Action para envío de mensajes en Telegram
on:
  push:
    branches:
      - send_telegram_action
jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  job2:
    name: Run
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: run action
        uses: Cristiannett/githubActions_examples@v2
        with:
          who-to-greet: "Cristiannett"
